export const midMajors = [1, 46, 5, 6, 9, 10, 45, 12, 13, 14, 16, 18, 19, 20, 22, 24, 25, 26, 49, 27, 29, 30];

export const majorConfs = [2, 62, 3, 8, 7, 4, 11, 44, 23, 21];

export const conferences = [
  {
    name: "A 10",
    id: 3
  },
  {
    name: "A-Sun",
    id: 46
  },
  {
    name: "ACC",
    id: 2
  },
  {
    name: "Am. East",
    id: 1
  },
  {
    name: "American",
    id: 62
  },
  {
    name: "Big 12",
    id: 8
  },
  {
    name: "Big East",
    id: 4
  },
  {
    name: "Big Sky",
    id: 5
  },
  {
    name: "Big South",
    id: 6
  },
  {
    name: "Big Ten",
    id: 7
  },
  {
    name: "Big West",
    id: 9
  },
  {
    name: "C-USA",
    id: 11
  },
  {
    name: "CAA",
    id: 10
  },
  {
    name: "Horizon",
    id: 45
  },
  {
    name: "Ivy",
    id: 12
  },
  {
    name: "MAAC",
    id: 13
  },
  {
    name: "MAC",
    id: 14
  },
  {
    name: "MEAC",
    id: 16
  },
  {
    name: "MVC",
    id: 18
  },
  {
    name: "MW",
    id: 44
  },
  {
    name: "NEC",
    id: 19
  },
  {
    name: "OVC",
    id: 20
  },
  {
    name: "Pac-12",
    id: 21
  },
  {
    name: "Patriot",
    id: 22
  },
  {
    name: "SEC",
    id: 23
  },
  {
    name: "SWAC",
    id: 26
  },
  {
    name: "Southern",
    id: 24
  },
  {
    name: "Southland",
    id: 25
  },
  {
    name: "Summit",
    id: 49
  },
  {
    name: "Sun Belt",
    id: 27
  },
  {
    name: "WAC",
    id: 30
  },
  {
    name: "WCC",
    id: 29
  }
];

export const teams = [
  { id: 2, location: "Auburn", abbrev: "AUB" },
  { id: 5, location: "UAB", abbrev: "UAB" },
  { id: 6, location: "South Alabama", abbrev: "USA" },
  { id: 8, location: "Arkansas", abbrev: "ARK" },
  { id: 9, location: "Arizona State", abbrev: "ASU", kpTeamName: "Arizona St." },
  { id: 12, location: "Arizona", abbrev: "ARIZ" },
  { id: 13, location: "Cal Poly", abbrev: "CP" },
  { id: 16, location: "Sacramento State", abbrev: "SAC", kpTeamName: "Sacramento St." },
  { id: 21, location: "San Diego State", abbrev: "SDSU", kpTeamName: "San Diego St." },
  { id: 23, location: "San Jose State", abbrev: "SJSU", kpTeamName: "San Jose St." },
  { id: 24, location: "Stanford", abbrev: "STAN" },
  { id: 25, location: "California", abbrev: "CAL" },
  { id: 26, location: "UCLA", abbrev: "UCLA" },
  { id: 27, location: "UC Riverside", abbrev: "UCRV" },
  { id: 30, location: "USC", abbrev: "USC" },
  { id: 36, location: "Colorado State", abbrev: "CSU", kpTeamName: "Colorado St." },
  { id: 38, location: "Colorado", abbrev: "COLO" },
  { id: 41, location: "Connecticut", abbrev: "CONN" },
  { id: 42, location: "Hartford", abbrev: "HART" },
  { id: 43, location: "Yale", abbrev: "YALE" },
  { id: 44, location: "American", abbrev: "AMER" },
  { id: 45, location: "George Washington", abbrev: "GW" },
  { id: 46, location: "Georgetown", abbrev: "GTWN" },
  { id: 47, location: "Howard", abbrev: "HOW" },
  { id: 48, location: "Delaware", abbrev: "DEL" },
  { id: 50, location: "Florida A&M", abbrev: "FAMU" },
  { id: 52, location: "Florida State", abbrev: "FSU", kpTeamName: "Florida St." },
  { id: 55, location: "Jacksonville State", abbrev: "JVST", kpTeamName: "Jacksonville St." },
  { id: 56, location: "Stetson", abbrev: "STET" },
  { id: 57, location: "Florida", abbrev: "FLA" },
  { id: 58, location: "South Florida", abbrev: "USF" },
  { id: 59, location: "Georgia Tech", abbrev: "GT" },
  { id: 61, location: "Georgia", abbrev: "UGA" },
  { id: 62, location: "Hawai'i", abbrev: "HAW", kpTeamName: "Hawaii" },
  { id: 66, location: "Iowa State", abbrev: "ISU", kpTeamName: "Iowa St." },
  { id: 68, location: "Boise State", abbrev: "BSU", kpTeamName: "Boise St." },
  { id: 70, location: "Idaho", abbrev: "IDHO" },
  { id: 71, location: "Bradley", abbrev: "BRAD" },
  { id: 77, location: "Northwestern", abbrev: "NW" },
  { id: 79, location: "Southern Illinois", abbrev: "SIU" },
  { id: 82, location: "UIC", abbrev: "UIC", kpTeamName: "Illinois Chicago" },
  { id: 84, location: "Indiana", abbrev: "IND" },
  { id: 85, location: "IUPUI", abbrev: "IUPU" },
  { id: 87, location: "Notre Dame", abbrev: "ND" },
  { id: 93, location: "Murray State", abbrev: "MURR", kpTeamName: "Murray St." },
  { id: 94, location: "Northern Kentucky", abbrev: "NKU" },
  { id: 96, location: "Kentucky", abbrev: "UK" },
  { id: 97, location: "Louisville", abbrev: "LOU" },
  { id: 98, location: "Western Kentucky", abbrev: "WKU" },
  { id: 99, location: "LSU", abbrev: "LSU" },
  { id: 103, location: "Boston College", abbrev: "BC" },
  { id: 104, location: "Boston University", abbrev: "BU" },
  { id: 107, location: "Holy Cross", abbrev: "HC" },
  { id: 108, location: "Harvard", abbrev: "HARV" },
  { id: 111, location: "Northeastern", abbrev: "NE" },
  { id: 113, location: "Massachusetts", abbrev: "UMASS" },
  { id: 116, location: "Mt. St. Mary's", abbrev: "MSM", kpTeamName: "Mount St. Mary's" },
  { id: 119, location: "Towson", abbrev: "TOWS" },
  { id: 120, location: "Maryland", abbrev: "MD" },
  { id: 127, location: "Michigan State", abbrev: "MSU", kpTeamName: "Michigan St." },
  { id: 130, location: "Michigan", abbrev: "MICH" },
  { id: 135, location: "Minnesota", abbrev: "MINN" },
  { id: 139, location: "Saint Louis", abbrev: "SLU" },
  { id: 140, location: "UMKC", abbrev: "UMKC" },
  { id: 142, location: "Missouri", abbrev: "MIZ" },
  { id: 145, location: "Ole Miss", abbrev: "MISS", kpTeamName: "Mississippi" },
  { id: 147, location: "Montana State", abbrev: "MTST", kpTeamName: "Montana St." },
  { id: 149, location: "Montana", abbrev: "MONT" },
  { id: 150, location: "Duke", abbrev: "DUKE" },
  { id: 151, location: "East Carolina", abbrev: "ECU" },
  { id: 152, location: "NC State", abbrev: "NCST", kpTeamName: "North Carolina St." },
  { id: 153, location: "North Carolina", abbrev: "UNC" },
  { id: 154, location: "Wake Forest", abbrev: "WAKE" },
  { id: 155, location: "North Dakota", abbrev: "UND" },
  { id: 156, location: "Creighton", abbrev: "CREI" },
  { id: 158, location: "Nebraska", abbrev: "NEB" },
  { id: 159, location: "Dartmouth", abbrev: "DART" },
  { id: 160, location: "New Hampshire", abbrev: "UNH" },
  { id: 161, location: "Fairleigh Dickinson", abbrev: "FDU" },
  { id: 163, location: "Princeton", abbrev: "PRIN" },
  { id: 164, location: "Rutgers", abbrev: "RUTG" },
  { id: 166, location: "New Mexico State", abbrev: "NMSU", kpTeamName: "New Mexico St." },
  { id: 167, location: "New Mexico", abbrev: "UNM" },
  { id: 171, location: "Columbia", abbrev: "CLMB" },
  { id: 172, location: "Cornell", abbrev: "COR" },
  { id: 179, location: "St. Bonaventure", abbrev: "SBON" },
  { id: 183, location: "Syracuse", abbrev: "SYR" },
  { id: 189, location: "Bowling Green", abbrev: "BGSU" },
  { id: 193, location: "Miami (OH)", abbrev: "M-OH", kpTeamName: "Miami OH" },
  { id: 194, location: "Ohio State", abbrev: "OSU", kpTeamName: "Ohio St." },
  { id: 195, location: "Ohio", abbrev: "OHIO" },
  { id: 197, location: "Oklahoma State", abbrev: "OKST", kpTeamName: "Oklahoma St." },
  { id: 198, location: "Oral Roberts", abbrev: "ORU" },
  { id: 201, location: "Oklahoma", abbrev: "OKLA" },
  { id: 202, location: "Tulsa", abbrev: "TLSA" },
  { id: 204, location: "Oregon State", abbrev: "ORST", kpTeamName: "Oregon St." },
  { id: 213, location: "Penn State", abbrev: "PSU", kpTeamName: "Penn St." },
  { id: 218, location: "Temple", abbrev: "TEM" },
  { id: 219, location: "Pennsylvania", abbrev: "PENN", kpTeamName: "Penn" },
  { id: 221, location: "Pittsburgh", abbrev: "PITT" },
  { id: 222, location: "Villanova", abbrev: "VILL" },
  { id: 225, location: "Brown", abbrev: "BRWN" },
  { id: 227, location: "Rhode Island", abbrev: "URI" },
  { id: 228, location: "Clemson", abbrev: "CLEM" },
  { id: 231, location: "Furman", abbrev: "FUR" },
  { id: 232, location: "Charleston", abbrev: "COFC", kpTeamName: "College of Charleston" },
  { id: 233, location: "South Dakota", abbrev: "SDAK" },
  { id: 235, location: "Memphis", abbrev: "MEM" },
  { id: 236, location: "Chattanooga", abbrev: "CHAT" },
  { id: 238, location: "Vanderbilt", abbrev: "VAN" },
  { id: 239, location: "Baylor", abbrev: "BAY" },
  { id: 242, location: "Rice", abbrev: "RICE" },
  { id: 245, location: "Texas A&M", abbrev: "TAMU" },
  { id: 248, location: "Houston", abbrev: "HOU" },
  { id: 249, location: "North Texas", abbrev: "UNT" },
  { id: 250, location: "UT Arlington", abbrev: "UTA" },
  { id: 251, location: "Texas", abbrev: "TEX" },
  { id: 252, location: "BYU", abbrev: "BYU" },
  { id: 253, location: "Southern Utah", abbrev: "SUU" },
  { id: 254, location: "Utah", abbrev: "UTAH" },
  { id: 256, location: "James Madison", abbrev: "JMU" },
  { id: 257, location: "Richmond", abbrev: "RICH" },
  { id: 258, location: "Virginia", abbrev: "UVA" },
  { id: 259, location: "Virginia Tech", abbrev: "VT" },
  { id: 261, location: "Vermont", abbrev: "UVM" },
  { id: 264, location: "Washington", abbrev: "WASH" },
  { id: 265, location: "Washington State", abbrev: "WSU", kpTeamName: "Washington St." },
  { id: 269, location: "Marquette", abbrev: "MARQ" },
  { id: 270, location: "Milwaukee", abbrev: "MILW" },
  { id: 275, location: "Wisconsin", abbrev: "WIS" },
  { id: 276, location: "Marshall", abbrev: "MRSH" },
  { id: 277, location: "West Virginia", abbrev: "WVU" },
  { id: 278, location: "Fresno State", abbrev: "FRES", kpTeamName: "Fresno St." },
  { id: 279, location: "Pacific", abbrev: "PAC" },
  { id: 282, location: "Indiana State", abbrev: "INST", kpTeamName: "Indiana St." },
  { id: 288, location: "Lipscomb", abbrev: "LIP" },
  { id: 290, location: "Georgia Southern", abbrev: "GASO" },
  { id: 292, location: "UT Rio Grande Valley", abbrev: "TRGV" },
  { id: 294, location: "Jacksonville", abbrev: "JAC" },
  { id: 295, location: "Old Dominion", abbrev: "ODU" },
  { id: 299, location: "Long Beach State", abbrev: "LBSU", kpTeamName: "Long Beach St." },
  { id: 300, location: "UC Irvine", abbrev: "UCI" },
  { id: 301, location: "San Diego", abbrev: "USD" },
  { id: 302, location: "UC Davis", abbrev: "UCD" },
  { id: 304, location: "Idaho State", abbrev: "IDST", kpTeamName: "Idaho St." },
  { id: 305, location: "DePaul", abbrev: "DEP" },
  { id: 309, location: "Louisiana", abbrev: "ULL", kpTeamName: "Louisiana Lafayette" },
  { id: 311, location: "Maine", abbrev: "MAINE" },
  { id: 314, location: "Iona", abbrev: "IONA" },
  { id: 315, location: "Niagara", abbrev: "NIAG" },
  { id: 322, location: "Lafayette", abbrev: "LAF" },
  { id: 324, location: "Coastal Carolina", abbrev: "CCAR" },
  { id: 325, location: "Cleveland State", abbrev: "CLEV", kpTeamName: "Cleveland St." },
  { id: 326, location: "Texas State", abbrev: "TXST", kpTeamName: "Texas St." },
  { id: 328, location: "Utah State", abbrev: "USU", kpTeamName: "Utah St." },
  { id: 331, location: "Eastern Washington", abbrev: "EWU" },
  { id: 333, location: "Alabama", abbrev: "ALA" },
  { id: 338, location: "Kennesaw State", abbrev: "KENN", kpTeamName: "Kennesaw St." },
  { id: 339, location: "Evansville", abbrev: "EVAN" },
  { id: 344, location: "Mississippi State", abbrev: "MSST", kpTeamName: "Mississippi St." },
  { id: 349, location: "Army", abbrev: "ARMY" },
  { id: 350, location: "UNC Wilmington", abbrev: "UNCW" },
  { id: 356, location: "Illinois", abbrev: "ILL" },
  { id: 357, location: "Texas A&M-CC", abbrev: "AMCC", kpTeamName: "Texas A&M Corpus Chris" },
  { id: 399, location: "Albany", abbrev: "ALBY" },
  { id: 526, location: "Florida Gulf Coast", abbrev: "FGCU" },
  { id: 2000, location: "Abilene Christian", abbrev: "ACU" },
  { id: 2005, location: "Air Force", abbrev: "AFA" },
  { id: 2006, location: "Akron", abbrev: "AKR" },
  { id: 2010, location: "Alabama A&M", abbrev: "AAMU" },
  { id: 2011, location: "Alabama State", abbrev: "ALST", kpTeamName: "Alabama St." },
  { id: 2016, location: "Alcorn State", abbrev: "ALCN", kpTeamName: "Alcorn St." },
  { id: 2026, location: "Appalachian State", abbrev: "APP", kpTeamName: "Appalachian St." },
  { id: 2029, location: "Arkansas-Pine Bluff", abbrev: "UAPB", kpTeamName: "Arkansas Pine Bluff" },
  { id: 2031, location: "Little Rock", abbrev: "UALR" },
  { id: 2032, location: "Arkansas State", abbrev: "ARST", kpTeamName: "Arkansas St." },
  { id: 2046, location: "Austin Peay", abbrev: "PEAY" },
  { id: 2050, location: "Ball State", abbrev: "BALL", kpTeamName: "Ball St." },
  { id: 2057, location: "Belmont", abbrev: "BEL" },
  { id: 2065, location: "Bethune-Cookman", abbrev: "BCU", kpTeamName: "Bethune Cookman" },
  { id: 2066, location: "Binghamton", abbrev: "BING" },
  { id: 2083, location: "Bucknell", abbrev: "BUCK" },
  { id: 2084, location: "Buffalo", abbrev: "BUFF" },
  { id: 2086, location: "Butler", abbrev: "BUT" },
  { id: 2097, location: "Campbell", abbrev: "CAM" },
  { id: 2099, location: "Canisius", abbrev: "CAN" },
  { id: 2110, location: "Central Arkansas", abbrev: "UCA" },
  { id: 2115, location: "Central Connecticut", abbrev: "CCSU" },
  { id: 2116, location: "UCF", abbrev: "UCF" },
  { id: 2117, location: "Central Michigan", abbrev: "CMU" },
  { id: 2127, location: "Charleston Southern", abbrev: "CHSO" },
  { id: 2130, location: "Chicago State", abbrev: "CHS", kpTeamName: "Chicago St." },
  { id: 2132, location: "Cincinnati", abbrev: "CIN" },
  { id: 2142, location: "Colgate", abbrev: "COLG" },
  { id: 2154, location: "Coppin State", abbrev: "COPP", kpTeamName: "Coppin St." },
  { id: 2166, location: "Davidson", abbrev: "DAV" },
  { id: 2168, location: "Dayton", abbrev: "DAY" },
  { id: 2169, location: "Delaware State", abbrev: "DSU", kpTeamName: "Delaware St." },
  { id: 2172, location: "Denver", abbrev: "DEN" },
  { id: 2174, location: "Detroit Mercy", abbrev: "DET", kpTeamName: "Detroit" },
  { id: 2181, location: "Drake", abbrev: "DRKE" },
  { id: 2182, location: "Drexel", abbrev: "DREX" },
  { id: 2184, location: "Duquesne", abbrev: "DUQ" },
  { id: 2193, location: "East Tennessee State", abbrev: "ETSU", kpTeamName: "East Tennessee St." },
  { id: 2197, location: "Eastern Illinois", abbrev: "EIU" },
  { id: 2198, location: "Eastern Kentucky", abbrev: "EKY" },
  { id: 2199, location: "Eastern Michigan", abbrev: "EMU" },
  { id: 2210, location: "Elon", abbrev: "ELON" },
  { id: 2217, location: "Fairfield", abbrev: "FAIR" },
  { id: 2226, location: "Florida Atlantic", abbrev: "FAU" },
  { id: 2229, location: "Florida Intl", abbrev: "FIU", kpTeamName: "FIU" },
  { id: 2230, location: "Fordham", abbrev: "FOR" },
  { id: 2239, location: "CS Fullerton", abbrev: "CSF", kpTeamName: "Cal St. Fullerton" },
  { id: 2241, location: "Gardner-Webb", abbrev: "WEBB", kpTeamName: "Gardner Webb" },
  { id: 2244, location: "George Mason", abbrev: "GMU" },
  { id: 2247, location: "Georgia State", abbrev: "GAST", kpTeamName: "Georgia St." },
  { id: 2250, location: "Gonzaga", abbrev: "GONZ" },
  { id: 2253, location: "Grand Canyon", abbrev: "GCU" },
  { id: 2261, location: "Hampton", abbrev: "HAMP" },
  { id: 2272, location: "High Point", abbrev: "HP" },
  { id: 2275, location: "Hofstra", abbrev: "HOF" },
  { id: 2277, location: "Houston Baptist", abbrev: "HBU" },
  { id: 2287, location: "Illinois State", abbrev: "ILST", kpTeamName: "Illinois St." },
  { id: 2294, location: "Iowa", abbrev: "IOWA" },
  { id: 2296, location: "Jackson State", abbrev: "JKST", kpTeamName: "Jackson St." },
  { id: 2305, location: "Kansas", abbrev: "KU" },
  { id: 2306, location: "Kansas State", abbrev: "KSU", kpTeamName: "Kansas St." },
  { id: 2309, location: "Kent State", abbrev: "KENT", kpTeamName: "Kent St." },
  { id: 2320, location: "Lamar", abbrev: "LAM" },
  { id: 2325, location: "La Salle", abbrev: "LAS" },
  { id: 2329, location: "Lehigh", abbrev: "LEH" },
  { id: 2335, location: "Liberty", abbrev: "LIB" },
  { id: 2341, location: "LIU Brooklyn", abbrev: "LIU" },
  { id: 2344, location: "Longwood", abbrev: "LONG" },
  { id: 2348, location: "Louisiana Tech", abbrev: "LT" },
  { id: 2349, location: "UMass Lowell", abbrev: "UML" },
  { id: 2350, location: "Loyola-Chicago", abbrev: "L-IL", kpTeamName: "Loyola Chicago" },
  { id: 2351, location: "Loyola Marymount", abbrev: "LMU" },
  { id: 2352, location: "Loyola (MD)", abbrev: "L-MD", kpTeamName: "Loyola MD" },
  { id: 2363, location: "Manhattan", abbrev: "MAN" },
  { id: 2368, location: "Marist", abbrev: "MRST" },
  { id: 2377, location: "McNeese", abbrev: "MCNS", kpTeamName: "McNeese St." },
  { id: 2378, location: "UMBC", abbrev: "UMBC" },
  { id: 2379, location: "Maryland-Eastern Shore", abbrev: "UMES", kpTeamName: "Maryland Eastern Shore" },
  { id: 2382, location: "Mercer", abbrev: "MER" },
  { id: 2390, location: "Miami", abbrev: "MIA", kpTeamName: "Miami FL" },
  { id: 2393, location: "Middle Tennessee", abbrev: "MTU" },
  { id: 2400, location: "Mississippi Valley State", abbrev: "MVSU", kpTeamName: "Mississippi Valley St." },
  { id: 2405, location: "Monmouth", abbrev: "MONM" },
  { id: 2413, location: "Morehead State", abbrev: "MORE", kpTeamName: "Morehead St." },
  { id: 2415, location: "Morgan State", abbrev: "MORG", kpTeamName: "Morgan St." },
  { id: 2426, location: "Navy", abbrev: "NAVY" },
  { id: 2427, location: "UNC Asheville", abbrev: "UNCA" },
  { id: 2428, location: "North Carolina Central", abbrev: "NCCU" },
  { id: 2429, location: "Charlotte", abbrev: "CHAR" },
  { id: 2430, location: "UNC Greensboro", abbrev: "UNCG" },
  { id: 2433, location: "UL Monroe", abbrev: "ULM", kpTeamName: "Louisiana Monroe" },
  { id: 2437, location: "Omaha", abbrev: "OMA", kpTeamName: "Nebraska Omaha" },
  { id: 2439, location: "UNLV", abbrev: "UNLV" },
  { id: 2440, location: "Nevada", abbrev: "NEV" },
  { id: 2443, location: "New Orleans", abbrev: "UNO" },
  { id: 2447, location: "Nicholls", abbrev: "NICH", kpTeamName: "Nicholls St." },
  { id: 2448, location: "North Carolina A&T", abbrev: "NCAT" },
  { id: 2449, location: "North Dakota State", abbrev: "NDSU", kpTeamName: "North Dakota St." },
  { id: 2450, location: "Norfolk State", abbrev: "NSU", kpTeamName: "Norfolk St." },
  { id: 2454, location: "North Florida", abbrev: "UNF" },
  { id: 2458, location: "Northern Colorado", abbrev: "UNCO" },
  { id: 2459, location: "Northern Illinois", abbrev: "NIU" },
  { id: 2460, location: "Northern Iowa", abbrev: "UNI" },
  { id: 2463, location: "CSU Northridge", abbrev: "CSUN", kpTeamName: "Cal St. Northridge" },
  { id: 2464, location: "Northern Arizona", abbrev: "NAU" },
  { id: 2466, location: "Northwestern State", abbrev: "NWST", kpTeamName: "Northwestern St." },
  { id: 2473, location: "Oakland", abbrev: "OAK" },
  { id: 2483, location: "Oregon", abbrev: "ORE" },
  { id: 2492, location: "Pepperdine", abbrev: "PEPP" },
  { id: 2501, location: "Portland", abbrev: "PORT" },
  { id: 2502, location: "Portland St", abbrev: "PRST", kpTeamName: "Portland St." },
  { id: 2504, location: "Prairie View A&M", abbrev: "PV" },
  { id: 2506, location: "Presbyterian", abbrev: "PRE" },
  { id: 2507, location: "Providence", abbrev: "PROV" },
  { id: 2509, location: "Purdue", abbrev: "PUR" },
  { id: 2514, location: "Quinnipiac", abbrev: "QUIN" },
  { id: 2515, location: "Radford", abbrev: "RAD" },
  { id: 2520, location: "Rider", abbrev: "RID" },
  { id: 2523, location: "Robert Morris", abbrev: "RMU" },
  { id: 2529, location: "Sacred Heart", abbrev: "SHU" },
  { id: 2534, location: "Sam Houston State", abbrev: "SHSU", kpTeamName: "Sam Houston St." },
  { id: 2535, location: "Samford", abbrev: "SAM" },
  { id: 2539, location: "San Francisco", abbrev: "SF" },
  { id: 2540, location: "UC Santa Barbara", abbrev: "UCSB" },
  { id: 2541, location: "Santa Clara", abbrev: "SCU" },
  { id: 2542, location: "Savannah State", abbrev: "SAV", kpTeamName: "Savannah St." },
  { id: 2545, location: "SE Louisiana", abbrev: "SELA", kpTeamName: "Southeastern Louisiana" },
  { id: 2546, location: "Southeast Missouri State", abbrev: "SEMO", kpTeamName: "Southeast Missouri St." },
  { id: 2547, location: "Seattle", abbrev: "SEA" },
  { id: 2550, location: "Seton Hall", abbrev: "HALL" },
  { id: 2561, location: "Siena", abbrev: "SIE" },
  { id: 2565, location: "SIU-Edwardsville", abbrev: "SIUE", kpTeamName: "SIU Edwardsville" },
  { id: 2567, location: "SMU", abbrev: "SMU" },
  { id: 2569, location: "South Carolina State", abbrev: "SCST", kpTeamName: "South Carolina St." },
  { id: 2571, location: "South Dakota State", abbrev: "SDST", kpTeamName: "South Dakota St." },
  { id: 2572, location: "Southern Miss", abbrev: "USM" },
  { id: 2579, location: "South Carolina", abbrev: "SC" },
  { id: 2582, location: "Southern", abbrev: "SOU" },
  { id: 2597, location: "St. Francis (BKN)", abbrev: "SFNY", kpTeamName: "St. Francis NY" },
  { id: 2598, location: "St. Francis (PA)", abbrev: "SFU", kpTeamName: "St. Francis PA" },
  { id: 2599, location: "St. John's", abbrev: "SJU" },
  { id: 2603, location: "Saint Joseph's", abbrev: "JOES" },
  { id: 2608, location: "Saint Mary's", abbrev: "SMC" },
  { id: 2612, location: "Saint Peter's", abbrev: "SPU" },
  { id: 2617, location: "Stephen F. Austin", abbrev: "SFA" },
  { id: 2619, location: "Stony Brook", abbrev: "STON" },
  { id: 2623, location: "Missouri State", abbrev: "MOST", kpTeamName: "Missouri St." },
  { id: 2628, location: "TCU", abbrev: "TCU" },
  { id: 2630, location: "Tenn-Martin", abbrev: "UTM", kpTeamName: "Tennessee Martin" },
  { id: 2633, location: "Tennessee", abbrev: "TENN" },
  { id: 2634, location: "Tennessee State", abbrev: "TNST", kpTeamName: "Tennessee St." },
  { id: 2635, location: "Tennessee Tech", abbrev: "TNTC" },
  { id: 2636, location: "UT San Antonio", abbrev: "UTSA", kpTeamName: "UTSA" },
  { id: 2638, location: "UTEP", abbrev: "UTEP" },
  { id: 2640, location: "Texas Southern", abbrev: "TXSO" },
  { id: 2641, location: "Texas Tech", abbrev: "TTU" },
  { id: 2643, location: "The Citadel", abbrev: "CIT" },
  { id: 2649, location: "Toledo", abbrev: "TOL" },
  { id: 2653, location: "Troy", abbrev: "TROY" },
  { id: 2655, location: "Tulane", abbrev: "TULN" },
  { id: 2670, location: "VCU", abbrev: "VCU" },
  { id: 2674, location: "Valparaiso", abbrev: "VALP" },
  { id: 2678, location: "VMI", abbrev: "VMI" },
  { id: 2681, location: "Wagner", abbrev: "WAG" },
  { id: 2692, location: "Weber State", abbrev: "WEB", kpTeamName: "Weber St." },
  { id: 2710, location: "Western Illinois", abbrev: "WIU" },
  { id: 2711, location: "Western Michigan", abbrev: "WMU" },
  { id: 2717, location: "Western Carolina", abbrev: "WCU" },
  { id: 2724, location: "Wichita State", abbrev: "WICH", kpTeamName: "Wichita St." },
  { id: 2729, location: "William & Mary", abbrev: "WM" },
  { id: 2737, location: "Winthrop", abbrev: "WIN" },
  { id: 2739, location: "Green Bay", abbrev: "GB" },
  { id: 2747, location: "Wofford", abbrev: "WOF" },
  { id: 2750, location: "Wright State", abbrev: "WRST", kpTeamName: "Wright St." },
  { id: 2751, location: "Wyoming", abbrev: "WYO" },
  { id: 2752, location: "Xavier", abbrev: "XAV" },
  { id: 2754, location: "Youngstown State", abbrev: "YSU", kpTeamName: "Youngstown St." },
  { id: 2755, location: "Grambling", abbrev: "GRAM", kpTeamName: "Grambling St." },
  { id: 2803, location: "Bryant", abbrev: "BRY" },
  { id: 2870, location: "Fort Wayne", abbrev: "IPFW" },
  { id: 2885, location: "NJIT", abbrev: "NJIT" },
  { id: 2908, location: "South Carolina Upstate", abbrev: "UPST", kpTeamName: "USC Upstate" },
  { id: 2916, location: "Incarnate Word", abbrev: "IW" },
  { id: 2934, location: "CSU Bakersfield", abbrev: "CSB", kpTeamName: "Cal St. Bakersfield" },
  { id: 3084, location: "Utah Valley", abbrev: "UVU" }
];
