module.exports = {
	9: { kpTeamName: "Arizona St." },
	16: { kpTeamName: "Sacramento St." },
	21: { kpTeamName: "San Diego St." },
	23: { kpTeamName: "San Jose St." },
	36: { kpTeamName: "Colorado St." },
	52: { kpTeamName: "Florida St." },
	55: { kpTeamName: "Jacksonville St." },
	62: { kpTeamName: "Hawaii" },
	66: { kpTeamName: "Iowa St." },
	68: { kpTeamName: "Boise St." },
	82: { kpTeamName: "Illinois Chicago" },
	93: { kpTeamName: "Murray St." },
	116: { kpTeamName: "Mount St. Mary's" },
	127: { kpTeamName: "Michigan St." },
	145: { kpTeamName: "Mississippi" },
	147: { kpTeamName: "Montana St." },
	152: { kpTeamName: "North Carolina St." },
	166: { kpTeamName: "New Mexico St." },
	193: { kpTeamName: "Miami OH" },
	194: { kpTeamName: "Ohio St." },
	197: { kpTeamName: "Oklahoma St." },
	204: { kpTeamName: "Oregon St." },
	213: { kpTeamName: "Penn St." },
	219: { kpTeamName: "Penn" },
	232: { kpTeamName: "College of Charleston" },
	265: { kpTeamName: "Washington St." },
	278: { kpTeamName: "Fresno St." },
	282: { kpTeamName: "Indiana St." },
	299: { kpTeamName: "Long Beach St." },
	304: { kpTeamName: "Idaho St." },
	309: { kpTeamName: "Louisiana Lafayette" },
	325: { kpTeamName: "Cleveland St." },
	326: { kpTeamName: "Texas St." },
	328: { kpTeamName: "Utah St." },
	338: { kpTeamName: "Kennesaw St." },
	344: { kpTeamName: "Mississippi St." },
	357: { kpTeamName: "Texas A&M Corpus Chris" },
	2011: { kpTeamName: "Alabama St." },
	2016: { kpTeamName: "Alcorn St." },
	2026: { kpTeamName: "Appalachian St." },
	2029: { kpTeamName: "Arkansas Pine Bluff" },
	2032: { kpTeamName: "Arkansas St." },
	2050: { kpTeamName: "Ball St." },
	2065: { kpTeamName: "Bethune Cookman" },
	2130: { kpTeamName: "Chicago St." },
	2154: { kpTeamName: "Coppin St." },
	2169: { kpTeamName: "Delaware St." },
	2174: { kpTeamName: "Detroit" },
	2193: { kpTeamName: "East Tennessee St." },
	2229: { kpTeamName: "FIU" },
	2239: { kpTeamName: "Cal St. Fullerton" },
	2241: { kpTeamName: "Gardner Webb" },
	2247: { kpTeamName: "Georgia St." },
	2287: { kpTeamName: "Illinois St." },
	2296: { kpTeamName: "Jackson St." },
	2306: { kpTeamName: "Kansas St." },
	2309: { kpTeamName: "Kent St." },
	2350: { kpTeamName: "Loyola Chicago" },
	2352: { kpTeamName: "Loyola MD" },
	2377: { kpTeamName: "McNeese St." },
	2379: { kpTeamName: "Maryland Eastern Shore" },
	2390: { kpTeamName: "Miami FL" },
	2400: { kpTeamName: "Mississippi Valley St." },
	2413: { kpTeamName: "Morehead St." },
	2415: { kpTeamName: "Morgan St." },
	2433: { kpTeamName: "Louisiana Monroe" },
	2437: { kpTeamName: "Nebraska Omaha" },
	2447: { kpTeamName: "Nicholls St." },
	2449: { kpTeamName: "North Dakota St." },
	2450: { kpTeamName: "Norfolk St." },
	2463: { kpTeamName: "Cal St. Northridge" },
	2466: { kpTeamName: "Northwestern St." },
	2502: { kpTeamName: "Portland St." },
	2534: { kpTeamName: "Sam Houston St." },
	2542: { kpTeamName: "Savannah St." },
	2545: { kpTeamName: "Southeastern Louisiana" },
	2546: { kpTeamName: "Southeast Missouri St." },
	2565: { kpTeamName: "SIU Edwardsville" },
	2569: { kpTeamName: "South Carolina St." },
	2571: { kpTeamName: "South Dakota St." },
	2597: { kpTeamName: "St. Francis NY" },
	2598: { kpTeamName: "St. Francis PA" },
	2623: { kpTeamName: "Missouri St." },
	2630: { kpTeamName: "Tennessee Martin" },
	2634: { kpTeamName: "Tennessee St." },
	2636: { kpTeamName: "UTSA" },
	2692: { kpTeamName: "Weber St." },
	2724: { kpTeamName: "Wichita St." },
	2750: { kpTeamName: "Wright St." },
	2754: { kpTeamName: "Youngstown St." },
	2755: { kpTeamName: "Grambling St." },
	2908: { kpTeamName: "USC Upstate" },
	2934: { kpTeamName: "Cal St. Bakersfield" }
}
